surface: Relocate done_aux label
Older GCC versions fail to compile code with

surface.c: In function ‘__alloc_surface_data’:
surface.c:397:1: error: label at end of compound statement
  397 | done_aux:

Relocate done_aux to fix this trouble. Not sure why that changed in a newer
GCC.